name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: any
  http: ^0.13.4
  shared_preferences: any
  permission_handler: ^10.4.0
  go_router: any
  intl: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
