name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.4
  flutter_lints: ^4.0.0
  shared_preferences: ^2.0.15
  go_router:
  intl:

flutter:
  uses-material-design: true

  assets:
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png